name: "CI"
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  tests:
    strategy:
      matrix:
        python-version: [ 310 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            system-features = benchmark kvm

      - name: Run tests on Python${{ matrix.python-version }}
        run: |
          nix-shell --argstr pyVersion ${{ matrix.python-version }} --run \
          "pip install -e . && pip install -r requirements/test.txt && pip install -r requirements/extras/third_party.txt && pytest --cov=typeit"

      - name: Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          nix-shell --argstr pyVersion ${{ matrix.python-version }} --arg isDevEnv false --run "coveralls"
